config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  #root 'posts#home_page'
  #get '/help',            to: 'static_pages#help'
  get '/about',           to: 'static_pages#about'
  #get '/contact',         to: 'static_pages#contact'
  get '/login',           to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  # Incase new users need to be created
  #get  '/signup',         to: 'users#new'
  #post '/signup',         to: 'users#create'
  get '/contact',         to: 'messages#new', as: 'new_message'
  post '/contact',        to: 'messages#create', as: 'create_message'
  get '/error',           to: 'messages#error_page'
  get '/success',         to: 'messages#success_page'
  resources :users
  resources :posts
  resources :categories
end

app/models/message.rb
class Message < ApplicationRecord
    include ActiveModel::Model
    attr_accessor :name, :email, :content
    validates :content, presence: true
    validates :name,  presence: true, length: { maximum: 50 }
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 245 },
                      format: { with: EMAIL_REGEX }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def new
        @message = Message.new
    end
    
    def create
    @message = Message.new message_params

        if @message.valid?
            ContactMailer.contact(@message).deliver_now
            redirect_to  '/success'
        else
            redirect_to '/error'
           
        end
    end

  private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/error_page.html.erb
<div class="about-page-bkg">
<div class="center">
<h1 class="message-flash">Your message was unable to be sent, please verify that your information was entered correctly</h1>
<%= link_to "Go Back", new_message_path %>
</div>
</div>

app/views/messages/new.html.erb
<% provide(:title, "Contact") %>
<div class="hidden-overflow">
<div id="scene">


    <div class="col-md-4">
    </div>   
    
    <div class="col-md-4">
        &nbsp;
        <% @message = Message.new %>
<div class="center">
    <%= form_for @message, url: create_message_url do |f| %>
      <%= notice %>
      <%= @message.errors.full_messages.join(', ') %>

      <%= f.text_field :name, placeholder: 'name' %>
      <%= f.email_field :email, placeholder: 'email' %>
      <%= f.text_area :content, placeholder: 'message' %>
      <%= f.submit 'Send' %>
    <% end %>
</div>
    </div>
    
    <div class="col-md-4">
        <li class="layer" data-depth="0.80" friction="0.80"><img src="assets/saturn.png"></li>
    </div>






</div>
</div>

app/views/messages/success_page.html.erb
<div class="about-page-bkg">
<div class="center">
<h1 class="message-flash">Thank you for your message!</h1>
<%= link_to "Return to homepage", root_path %>
</div>
</div>