config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'
  #root 'posts#home_page'
  #get '/help',            to: 'static_pages#help'
  get '/about',           to: 'static_pages#about'
  #get '/contact',         to: 'static_pages#contact'
  get '/login',           to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  # Incase new users need to be created
  #get  '/signup',         to: 'users#new'
  #post '/signup',         to: 'users#create'
  get '/contact',         to: 'messages#new', as: 'new_message'
  post '/contact',        to: 'messages#create', as: 'create_message'
  get '/error',           to: 'messages#error_page'
  get '/success',         to: 'messages#success_page'
  resources :users
  resources :posts
  resources :categories
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <%= image_tag('moonicon.png', size: '25x25') %>
      </button>
      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <div class="center">
        <ul class="nav navbar-nav">
        
          <li><%= link_to "Home", root_path, class: "header-logo" %></li>
          <li><%= link_to "About", about_path, class: "header-logo" %></li>
          <li><%= link_to "Archives", posts_path, class: "header-logo" %></li>
          
          <% if logged_in? && current_user.admin? %>
            <%= render 'layouts/logged_in_header' %>
          <% end %>
          
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_logged_in_header.html.erb
<li><%= link_to "New Post", new_post_path, class: "header-logo" %></li>
<li><%= link_to "Edit Profile", edit_user_path(current_user), class: "header-logo" %></li>
<li><%= link_to "Log out", logout_path, method: "delete", class: "header-logo" %></li>

app/views/layouts/_menu.html.erb
<div class="menu-header" onclick="openNav()">Menu</div>

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <%= link_to "Home", root_path, id: "logo-four-phone" %>
      <%= link_to "Categories", categories_path, id: "logo-three-phone" %>
      <%= link_to "Archive", posts_path, id: "logo-three-phone" %>
      <% if logged_in? && current_user.admin? %>
        <%= link_to "Log out", logout_path, method: "delete", id: "logo-three-phone" %>
        <%= link_to "Edit Profile", edit_user_path(current_user), id: "logo-three-phone" %>
        <%= link_to "New Post", new_post_path, id: "logo-three-phone" %>
        <%= link_to "New Category", new_category_path, id: "logo-three-phone" %>
      <% end %>
</div>

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.body.style.backgroundColor = "white";
}
</script>

app/views/layouts/_phone_header.html.erb
<header class="navbar navbar-default navbar-static-top" id="phoneheaderbkg">
    <div class="container">
        <div class="row">
            <div id="logo">True</div>
            <div id="logo-two">Conspiracies</div>
        </div>
<br />
<%= render 'layouts/menu' %>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="column col-xs-3" id="sidebar">
        <div class="sidebar-nav-fixed pull-right affix">    
                <ul class="nav">
                    <div class="center">
                    <ul><h5>Categories</h5></ul>
                    <% @categories = Category.all.order(created_at: :desc) %>
                    <% @categories.each do |category| %>
                        <ul id="p-side">
                            <blog-headers><%= link_to "#{category.name}", category_path(category) %></blog-headers> 
                        </ul>
                    <% end %>
                    <% if logged_in? && current_user.admin? %>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false">
                                <ul id="p-side"><blog-headers>New Category</blog-headers></ul>
                            </button>
                            <div class="dropdown-menu"  aria-labelledby="dropdownMenuButton">
                                <% @category = Category.new %>
                                <%= simple_form_for(@category) do |f| %>
                                <p class="center"><%= f.error_notification %></p>
                                <p class="center"><%= f.input :name %></p>
                                <p class="center"><%= f.button :submit %></p>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                    </div>
                </ul>
        </div>    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Moon|Half" />
  <meta property="og:description"   content="Web Development Blog" />
  <meta property="og:image"         content="assets/moonicon.png" />
  <meta property="og:image" content="#{image_url('moonicon.png')}" />
  
  <meta name="viewport" content="width=device-width; height=device-height; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  <%= favicon_link_tag 'moonicon.png' %>
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/header' %>
     
      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/2.1.3/parallax.min.js"></script>
      <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
      
  </head>
  
  
    <body>
       <%= yield %>
      
      
    </body>
  
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Merienda" rel="stylesheet">
    
    <script>
      // Initialize Parallax.js
      var scene = document.getElementById('scene');
      var parallax = new Parallax(scene);
      
      // Touch Punch Draggable Letters
      for (var i = 0; i < 10; i++) {
        var x = document.getElementsByClassName("mydiv")[i]
        $(x).draggable();
      }
    </script>
    
    
</html>